### ISSUE TITLE
Crash when apply Furnace Upgrades on block different from Improved Furnace.

### ISSUE THREAD

**Issue by CrazyManLabs** [M4thG33k/LittleInsignificantThings_1.9#5]
As issue title states, there is one bug, that not so critical at the moment, but need fixing.
When I suddenly click on the ground (no matter which block, just not Improved Furnace) - game crashes with log:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.7.0.jar)
  DLFMLCorePlugin (DynamicLights-1.9.4.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  BCModPlugin (zz-backpacks 1.9.4 - 3.1.0.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 27.06.16 18:22
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at com.m4thg33k.lit.items.ItemFurnaceUpgrade.func_180614_a(ItemFurnaceUpgrade.java:39)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:143)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:445)
    at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1517)
    at net.minecraft.client.Minecraft.redirect$onRightClickMouse$0(Minecraft.java:146)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1748)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at com.m4thg33k.lit.items.ItemFurnaceUpgrade.func_180614_a(ItemFurnaceUpgrade.java:39)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:143)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:445)
    at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1517)
    at net.minecraft.client.Minecraft.redirect$onRightClickMouse$0(Minecraft.java:146)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)
```

MC-1.9.4
Forge-12.17.0.1976 (Stable)
LIT-1.9.4-2.0.1

**Comment by M4thG33k** [comment]
The next update fixes this. Thanks for letting me know!

**Comment by CrazyManLabs** [comment]
I think, this patch may help to fix this problem..

```
--- D:/ItemFurnaceUpgrade-old.java  Mon Jun 27 18:48:14 2016
+++ D:/ItemFurnaceUpgrade.java  Mon Jun 27 18:49:19 2016
@@ -36,20 +36,23 @@
     public EnumActionResult onItemUse(ItemStack stack, EntityPlayer playerIn, World worldIn, BlockPos pos, EnumHand hand, EnumFacing facing, float hitX, float hitY, float hitZ) {
         TileImprovedFurnace te = (TileImprovedFurnace)worldIn.getTileEntity(pos);

-        if (te.canReceiveUpgrade())
+        if (te != null)
         {
-            te.installUpgrade(playerIn,stack);
-            stack.stackSize--;
-            if (stack.stackSize==0)
+            if (te.canReceiveUpgrade())
             {
-                stack = null;
+                te.installUpgrade(playerIn,stack);
+                stack.stackSize--;
+                if (stack.stackSize==0)
+                {
+                    stack = null;
+                }
+                return EnumActionResult.SUCCESS;
+            }
+            else
+            {
+                ChatHelper.sayMessage(worldIn,playerIn,"No room for upgrades!");
+                return EnumActionResult.FAIL;
             }
-            return EnumActionResult.SUCCESS;
-        }
-        else
-        {
-            ChatHelper.sayMessage(worldIn,playerIn,"No room for upgrades!");
-            return EnumActionResult.FAIL;
         }
     }

```

But you already answered, sooo.. you already know about it. Thanks for fast reply :)
